name: 'PR Intent Checker'
description: 'Checks if PR code changes align with the linked issue intent using an LLM.'
author: 'Cline (AI Assistant)'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
  # Optional: Add inputs for model name, prompt path, etc. if needed later

outputs:
  result:
    description: 'The PASS/FAIL result from the LLM evaluation.'
  explanation:
    description: 'The explanation provided by the LLM for the result.'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'green'
